server:
  port: 8000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wallacejackson/project-spring-cloud.git
          search-paths: project-config-server/src/main/resources/configs
          default-label: master
