server:  
  port: 9000

eureka: 
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8001}/eureka/
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2 

spring:
    application:
        name: project-order-service
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: '1234'
        platform: mysql
        url: jdbc:mysql://localhost:7001/project_order?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: create
        show-sql: true